name: "Update cachix cache for bleeding edge"

on:
  push:
    branches:
      - main

jobs:
  r-update-cachix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - run:   |
         if [ "$RUNNER_OS" == "Linux" ]; then
              nix-build --argstr system x86_64-linux sf.nix
              nix-build --argstr system aarch64-linux sf.nix
         else
              nix-build sf.nix
         fi
