on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: nix-builder

jobs:
  run-x86_64-linux:
    name: nix builder for Ubuntu
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Nix metadata
      run: nix-shell -p nix-info --run "nix-info -m"
      
    - name: Run `nix-build default.nix`
      run: |
        nix-build default.nix

    - name: Quarto check
      run: |
        nix-shell default.nix

  run-aarch64-darwin:
    name: nix builder for darwin
    # the DeterminateSystems action currently uses macos-12
    # https://github.com/DeterminateSystems/nix-installer-action/blob/main/.github/workflows/ci.yml
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Nix metadata
      run: nix-shell -p nix-info --run "nix-info -m"
      
    - name: Run `nix-build default.nix`
      run: |
        nix-build default.nix
        
    - name: Quarto check
      run: |
        nix-shell default.nix
